//! Per-language builtin/type identifiers and special identifiers (self/this/etc.).

use super::language::Language;

impl Language {
    pub(super) fn builtins(&self) -> &[&str] {
        match self {
            Self::Rust => &[
                "String",
                "Vec",
                "Option",
                "Result",
                "Box",
                "Rc",
                "Arc",
                "HashMap",
                "HashSet",
                "println!",
                "eprintln!",
                "format!",
                "vec!",
                "panic!",
                "todo!",
                "unimplemented!",
                "assert!",
                "assert_eq!",
                "dbg!",
                "write!",
                "writeln!",
                "u8",
                "u16",
                "u32",
                "u64",
                "u128",
                "usize",
                "i8",
                "i16",
                "i32",
                "i64",
                "i128",
                "isize",
                "f32",
                "f64",
                "bool",
                "str",
                "char",
                "Self",
            ],
            Self::Python => &[
                "print",
                "len",
                "range",
                "enumerate",
                "zip",
                "map",
                "filter",
                "sorted",
                "reversed",
                "list",
                "dict",
                "set",
                "tuple",
                "str",
                "int",
                "float",
                "bool",
                "bytes",
                "isinstance",
                "issubclass",
                "type",
                "super",
                "property",
                "staticmethod",
                "classmethod",
                "open",
                "input",
                "abs",
                "min",
                "max",
                "sum",
                "any",
                "all",
                "iter",
                "next",
            ],
            Self::JavaScript | Self::TypeScript => &[
                "console",
                "Math",
                "JSON",
                "Array",
                "Object",
                "Map",
                "Set",
                "Promise",
                "parseInt",
                "parseFloat",
                "isNaN",
                "setTimeout",
                "setInterval",
                "string",
                "number",
                "boolean",
                "void",
                "never",
                "any",
                "unknown",
                "require",
                "module",
                "exports",
                "process",
                "Buffer",
            ],
            Self::Go => &[
                "make",
                "new",
                "append",
                "len",
                "cap",
                "copy",
                "delete",
                "close",
                "panic",
                "recover",
                "print",
                "println",
                "error",
                "string",
                "byte",
                "rune",
                "int",
                "int8",
                "int16",
                "int32",
                "int64",
                "uint",
                "uint8",
                "uint16",
                "uint32",
                "uint64",
                "float32",
                "float64",
                "complex64",
                "complex128",
                "bool",
            ],
            _ => &[],
        }
    }

    pub(super) fn special_idents(&self) -> &[&str] {
        match self {
            Self::Rust => &["self", "super", "crate", "Self"],
            Self::Python => &["self", "cls", "__init__", "__main__", "__name__"],
            Self::JavaScript | Self::TypeScript => {
                &["this", "super", "globalThis", "window", "document"]
            }
            Self::Go => &["nil"],
            Self::Java => &["this", "super"],
            Self::Ruby => &["self", "super"],
            _ => &[],
        }
    }
}
